from __future__ import annotations
import argparse
import importlib.util
from pathlib import Path
from .builder import Portfolio

GENERATED_OUTPUT = Path("assets/data/projects.json")
GENERATED_SITE_OUTPUT = Path("assets/data/site.json")
GENERATED_PAGE_MARKER = "<!-- Generated by portfolio.py; do not edit. -->"


def clean_generated_output(output: str | Path = GENERATED_OUTPUT) -> bool:
    """Remove one generated data file and report whether it existed."""
    destination = Path(output)
    if not destination.exists():
        return False
    if not destination.is_file():
        raise ValueError(f"生成数据路径不是文件: {destination}")
    destination.unlink()
    return True


def clean_generated_pages(root: str | Path = ".") -> list[Path]:
    """Delete only HTML shells carrying the generator marker."""
    page_directory = Path(root) / "pages" / "projects"
    removed: list[Path] = []
    if not page_directory.is_dir():
        return removed
    for candidate in page_directory.glob("*.html"):
        if GENERATED_PAGE_MARKER in candidate.read_text(encoding="utf-8"):
            candidate.unlink()
            removed.append(candidate)
    return removed

def load_source(path: str) -> Portfolio:
    source = Path(path)
    if source.suffix == ".json": return Portfolio.load(source)
    spec = importlib.util.spec_from_file_location("portfolio_source", source)
    if not spec or not spec.loader: raise ValueError(f"无法加载内容源: {source}")
    module = importlib.util.module_from_spec(spec); spec.loader.exec_module(module)
    portfolio = getattr(module, "portfolio", None)
    if not isinstance(portfolio, Portfolio): raise ValueError("内容文件必须暴露 portfolio = Portfolio(...)")
    return portfolio

def main() -> int:
    parser = argparse.ArgumentParser(prog="portfolio-content")
    sub = parser.add_subparsers(dest="command", required=True)
    for name in ("validate", "build", "preview"): 
        command = sub.add_parser(name); command.add_argument("source"); command.add_argument("--output", default="assets/data/projects.json"); command.add_argument("--port", type=int, default=8000)
    sub.add_parser("clean", help="删除上一次构建生成的 assets/data/projects.json")
    args = parser.parse_args()
    try:
        if args.command == "clean":
            removed_data = clean_generated_output()
            removed_site = clean_generated_output(GENERATED_SITE_OUTPUT)
            removed_pages = clean_generated_pages()
            if removed_data or removed_site or removed_pages:
                print(f"已删除生成数据：JSON {int(removed_data) + int(removed_site)} 个，HTML {len(removed_pages)} 个")
            else:
                print("无需清理：没有找到 Python 生成的数据")
            return 0
        portfolio = load_source(args.source)
        report = portfolio.validate(root=Path.cwd())
        if not report.ok:
            print(report.format())
            return 1
        if args.command == "validate":
            print("内容校验通过")
            return 0
        portfolio.write(args.output, root=Path.cwd())
        site_output = portfolio.write_site_data()
        pages = portfolio.write_pages(root=Path.cwd())
        print(f"已生成 {args.output}")
        print(f"已生成 {site_output}")
        print(f"已生成 {len(pages)} 个项目详情页")
        if args.command == "preview":
            import functools
            import http.server
            print(f"预览地址：http://127.0.0.1:{args.port}/")
            http.server.test(HandlerClass=functools.partial(http.server.SimpleHTTPRequestHandler), port=args.port, bind="127.0.0.1")
        return 0
    except (OSError, ValueError, KeyError) as error:
        print(f"ERROR: {error}")
        return 1

if __name__ == "__main__": raise SystemExit(main())
