from __future__ import annotations

from calendar import month_abbr
from datetime import date as Date
from html import escape, unescape
from pathlib import Path
from typing import Any
import json
import os
import re
import tempfile

from .vendor import markdown2


MARKER = "<!-- Generated by portfolio.py; do not edit. -->"
SITE_ORIGIN = "https://hancheng-guo.github.io"
_UNDERLINE = re.compile(r"(?<![\w_])_(?!_)(?=\S)([^_\n]*?\S)_(?![\w_])")
_UNSAFE_HREF = re.compile(r'\s+href="(?!https?://|mailto:|tel:|#|/|\.\.?/)[^"]*"', re.I)


def localized(value: Any, language: str = "en") -> Any:
    if isinstance(value, dict) and ("en" in value or "zh" in value):
        return value.get(language, value.get("en", ""))
    return value


def _prepare_markdown(value: Any) -> str:
    text = str(localized(value) or "")
    return _UNDERLINE.sub(lambda match: f"MDUNDERLINEOPEN{match.group(1)}MDUNDERLINECLOSE", text)


def markdown_block(value: Any) -> str:
    rendered = str(markdown2.markdown(
        _prepare_markdown(value),
        safe_mode="escape",
        extras=["break-on-newline", "cuddled-lists", "fenced-code-blocks", "strike", "tables"],
    ))
    rendered = rendered.replace("MDUNDERLINEOPEN", "<u>").replace("MDUNDERLINECLOSE", "</u>")
    return _UNSAFE_HREF.sub("", rendered).strip()


def markdown_inline(value: Any) -> str:
    rendered = markdown_block(value)
    if rendered.startswith("<p>") and rendered.endswith("</p>") and rendered.count("<p>") == 1:
        return rendered[3:-4].rstrip("\n")
    return rendered


def markdown_plain(value: Any) -> str:
    return unescape(re.sub(r"<[^>]+>", "", markdown_inline(value)))


def markdown_text(value: Any) -> str:
    return escape(markdown_plain(value), quote=True)


def format_month(value: str, language: str = "en") -> str:
    year, month = (int(part) for part in value.split("-"))
    return f"{year}年{month}月" if language == "zh" else f"{month_abbr[month]} {year}"


def format_date_range(value: Any, language: str = "en") -> str:
    if not value:
        return ""
    if isinstance(value, str):
        start, end = value, None
    else:
        start, end = value.get("start"), value.get("end")
    if not start:
        return ""
    start_text = format_month(start, language)
    return f"{start_text} – {format_month(end, language)}" if end and end != start else start_text


def format_full_date(value: str, language: str = "en") -> str:
    parsed = Date.fromisoformat(value)
    return f"{parsed.year}年{parsed.month}月{parsed.day}日" if language == "zh" else f"{month_abbr[parsed.month]} {parsed.day}, {parsed.year}"


def _icon(name: str) -> str:
    safe_name = re.sub(r"[^a-z0-9-]", "", name.lower())
    return f'<span class="svg-icon icon-{safe_name}" aria-hidden="true"></span>'


def _favicon(path: str | None, prefix: str) -> str:
    return f'  <link rel="icon" href="{prefix}{escape(path, quote=True)}">\n' if path else ""


def _metadata(
    *,
    title: Any,
    description: Any,
    canonical_path: str,
    og_type: str,
    image_path: str | None = None,
    structured_data: dict[str, Any] | None = None,
) -> str:
    safe_title = markdown_text(title)
    safe_description = markdown_text(description)
    canonical = f"{SITE_ORIGIN}/{canonical_path.lstrip('/')}" if canonical_path else f"{SITE_ORIGIN}/"
    image = f'<meta property="og:image" content="{SITE_ORIGIN}/{escape(image_path, quote=True)}">' if image_path else ""
    structured = ""
    if structured_data:
        payload = json.dumps(structured_data, ensure_ascii=False, separators=(",", ":")).replace("<", "\\u003c")
        structured = f'<script type="application/ld+json">{payload}</script>'
    return f'''<meta name="description" content="{safe_description}">
<meta property="og:title" content="{safe_title}">
<meta property="og:description" content="{safe_description}">
<meta property="og:type" content="{escape(og_type, quote=True)}">
<meta property="og:url" content="{canonical}">
{image}<link rel="canonical" href="{canonical}">
{structured}'''


def _theme_button() -> str:
    return '<button class="control-btn theme-toggle" type="button" aria-label="Toggle color theme" data-i18n-aria-label="nav.toggleTheme">' + _icon("sun").replace('class="svg-icon', 'class="svg-icon sun-icon') + _icon("moon").replace('class="svg-icon', 'class="svg-icon moon-icon') + "</button>"


def _anchor_bootstrap() -> str:
    """Hide a cross-document non-top fragment until its static target is ready.

    This is deliberately inline and precedes the stylesheet: the browser can
    perform its native fragment scroll during parsing without ever exposing a
    top-of-page frame.  The timeout is a no-JS-error safety net.
    """
    return '''<style>html[data-anchor-pending] body{opacity:0}html[data-anchor-pending].anchor-ready body{opacity:1;transition:opacity .14s ease}</style><script>(function(){var r=document.documentElement,h=location.hash;if(!h||h==='#top'||(matchMedia&&matchMedia('(prefers-reduced-motion: reduce)').matches))return;r.dataset.anchorPending='true';setTimeout(function(){r.classList.add('anchor-ready')},350)})()</script>'''


def _nav(portfolio: Any, prefix: str, *, active_cv: bool = False) -> str:
    author = markdown_inline(portfolio.author)
    home = f"{prefix}index.html"
    cv = f"{prefix}pages/cv.html"
    active = ' class="active"' if active_cv else ""
    return f'''<nav><div class="container nav-container">
  <a href="{home}" class="logo"><span class="logo-text">{author}</span><div class="logo-dot"></div></a>
  <div class="nav-actions"><button class="control-btn menu-toggle" type="button" aria-expanded="false" aria-controls="primary-navigation" aria-label="Open navigation" data-i18n-aria-label="nav.openMenu">☰</button>
    <div class="nav-links" id="primary-navigation"><a href="{home}#top" data-i18n="nav.portfolio">Portfolio</a><a href="{home}#projects" data-i18n="nav.project">Project</a><a href="{home}#publications" data-i18n="nav.publications">Publications</a><a href="{home}#timeline" data-i18n="nav.timeline">Timeline</a><a href="{cv}"{active} data-i18n="nav.resume">CV</a></div>
    <div class="nav-controls"><button class="control-btn lang-toggle" type="button" aria-label="Toggle language" data-i18n-aria-label="nav.toggleLanguage">中文</button>{_theme_button()}</div>
  </div>
</div></nav>'''


def _footer(portfolio: Any) -> str:
    author = markdown_inline(portfolio.author)
    copyright_text = markdown_inline(portfolio.copyright_text)
    suffix = f", {copyright_text}" if copyright_text else ""
    updated = format_full_date(portfolio.last_update_date)
    return f'<footer><span class="footer-copyright">© {portfolio.last_update_date[:4]} {author}{suffix}</span><span class="footer-updated">Site last updated {updated}</span></footer>'


def _download(resume: dict[str, Any], prefix: str) -> str:
    url = localized(resume.get("url"))
    if not url:
        return ""
    external = str(url).startswith(("http://", "https://"))
    href = str(url) if external else prefix + str(url)
    attrs = ' target="_blank" rel="noopener noreferrer"' if external else (' download' if resume.get("download", True) else "")
    label = markdown_inline(resume.get("label") or "Download CV")
    return f'<a class="publish-link primary-action" href="{escape(href, quote=True)}"{attrs}>{_icon("file-pdf")}<span>{label}</span></a>'


def _contacts(portfolio: Any, prefix: str = "") -> str:
    parts: list[str] = []
    email = localized(portfolio.profile.get("email"))
    if email:
        safe_email = escape(str(email), quote=True)
        parts.append(f'<div class="contact-item email-contact-item"><a class="email-contact-link" href="mailto:{safe_email}" aria-label="{safe_email}">{_icon("envelope")}<span>{escape(str(email))}</span></a></div>')
    social = []
    for contact in portfolio.contacts:
        label = markdown_inline(contact.get("label"))
        plain_label = markdown_text(contact.get("label"))
        social.append(f'<div class="contact-item"><a href="{escape(str(contact.get("url", "")), quote=True)}" aria-label="{plain_label}" title="{plain_label}" target="_blank" rel="noopener noreferrer">{_icon(str(contact.get("icon", "")))}<span class="visually-hidden">{label}</span></a></div>')
    if social:
        parts.append('<div class="social-contact-group">' + "".join(social) + "</div>")
    return "".join(parts)


def _entry(entry: dict[str, Any], title_field: str, detail_fields: tuple[str, ...]) -> str:
    title = markdown_inline(entry.get(title_field, ""))
    date_text = format_date_range(entry.get("date"))
    details = [markdown_inline(entry.get(field, "")) for field in detail_fields if localized(entry.get(field, ""))]
    pieces: list[str] = []
    if date_text:
        pieces.append(f'<time class="entry-date">{escape(date_text)}</time>')
    pieces.extend(f'<span class="entry-detail">{detail}</span>' for detail in details)
    detail_html = '<span class="entry-separator"> · </span>'.join(pieces)
    details = f'<p>{detail_html}</p>' if detail_html else ""
    return f'<article class="content-entry"><h3>{title}</h3>{details}</article>'


def _publication_entries(items: list[dict[str, Any]]) -> str:
    return "".join(_entry(item, "title", ("venue",)) for item in items)


def _project_card(project: dict[str, Any]) -> str:
    content = project["locales"]["en"]
    date_text = format_date_range(project.get("date"))
    tags = "".join(f'<span class="project-tag">{markdown_inline(tag)}</span>' for tag in project.get("tags", []))
    href = escape(str(project["page"]), quote=True)
    image = project.get("thumbnail", {})
    alt = markdown_text(localized(image.get("alt")))
    # The hidden time is deliberately retained for undated projects.  The
    # client renderer uses this exact node too, which prevents hydration from
    # changing the footer's layout or DOM shape.
    date_element = f'<time class="project-date">{escape(date_text)}</time>' if date_text else '<time class="project-date" hidden></time>'
    return f'''<article class="card" tabindex="0" data-project-href="{href}"><div class="project-thumbnail-wrapper"><img class="project-thumbnail" src="{escape(str(image.get("src", "")), quote=True)}" alt="{alt}" loading="lazy" decoding="async"></div><div class="project-info"><h3>{markdown_inline(content.get("title"))}</h3><p class="project-summary">{markdown_inline(content.get("summary"))}</p><div class="project-tags">{tags}</div><div class="project-card-footer"><a class="project-link" href="{href}">View Details</a>{date_element}</div></div></article>'''


def _timeline(portfolio: Any) -> tuple[str, bool]:
    events = list(reversed(portfolio.timeline))
    parts = []
    for index, event in enumerate(events):
        extra = " timeline-extra" if index >= 8 else ""
        parts.append(f'<div class="timeline-item{extra}"><div class="timeline-dot"></div><div class="timeline-summary"><span class="timeline-date">{escape(format_date_range(event.get("date")))}</span><h3>{markdown_inline(event.get("title"))}</h3></div><div class="timeline-content"><p>{markdown_inline(event.get("description"))}</p></div></div>')
    return "".join(parts), len(events) > 8


def render_home(portfolio: Any) -> str:
    profile = portfolio.profile
    name = markdown_inline(profile.get("name", portfolio.author))
    summary = markdown_inline(profile.get("summary", ""))
    projects = "".join(_project_card(project) for project in portfolio.projects if project.get("status") != "draft")
    journals = _publication_entries(portfolio.publications.get("journalArticles", []))
    conferences = _publication_entries(portfolio.publications.get("conferencePapers", []))
    timeline, has_more = _timeline(portfolio)
    toggle_attrs = "" if has_more else " hidden"
    favicon = _favicon(portfolio.favicon, "")
    title = markdown_text(portfolio.site_name)
    metadata = _metadata(
        title=portfolio.site_name,
        description=profile.get("summary", ""),
        canonical_path="",
        og_type="website",
        image_path="assets/images/Avatar.jpg",
        structured_data={
            "@context": "https://schema.org",
            "@type": "Person",
            "name": markdown_plain(profile.get("name", portfolio.author)),
            "url": f"{SITE_ORIGIN}/",
        },
    )
    return f'''<!DOCTYPE html>
{MARKER}
<html lang="en" data-theme="dark"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{title}</title>{metadata}{favicon}<script>document.documentElement.setAttribute('data-theme', localStorage.getItem('theme') || 'dark');</script>{_anchor_bootstrap()}<link rel="stylesheet" href="assets/css/style.css"></head>
<body id="top" data-page="home">{_nav(portfolio, "")}
<main><section class="intro"><div class="bg-decoration"></div><div class="container flex-center column"><div class="avatar-container"><div class="avatar-glow"></div><img class="avatar" src="assets/images/Avatar.jpg" alt="{markdown_text(profile.get("name", portfolio.author))} profile portrait"></div><h1 class="gradient-text hero-title">Hello, I'm {name}</h1><div class="subtitle hero-summary">{summary}</div><div class="hero-action-row"><div class="intro-actions">{_download(portfolio.resume, "")}</div><div id="contact" class="contact-links hero-contact-links" aria-label="Contact links">{_contacts(portfolio)}</div></div></div></section>
<section id="projects" class="section-padding"><div class="container"><h2 data-i18n="projects.title">Projects</h2><div class="projects-grid">{projects}</div></div></section>
<section id="publications" class="section-padding"><div class="container"><h2 data-i18n="publications.title">Publications</h2><div class="narrative-container"><h3 data-i18n="publications.journal">Journal Articles</h3><div class="content-list home-journals">{journals}</div><h3 data-i18n="publications.conference">Conference Papers</h3><div class="content-list home-conferences">{conferences}</div></div></div></section>
<section id="timeline" class="section-padding"><div class="container"><h2 data-i18n="timeline.title">Timeline</h2><div class="timeline-container">{timeline}</div><button class="control-btn timeline-toggle" type="button" aria-expanded="false"{toggle_attrs} data-i18n="timeline.showMore">Show more</button></div></section></main>
{_footer(portfolio)}<script type="module" src="assets/js/app.js"></script></body></html>'''


def render_cv(portfolio: Any) -> str:
    profile = portfolio.profile
    favicon = _favicon(portfolio.favicon, "../")
    education = "".join(_entry(item, "institution", ("degree",)) for item in portfolio.education)
    work = "".join(_entry(item, "title", ("organization", "summary")) for item in portfolio.work_experience)
    awards = "".join(_entry(item, "title", ()) for item in portfolio.awards)
    journals = _publication_entries(portfolio.publications.get("journalArticles", []))
    conferences = _publication_entries(portfolio.publications.get("conferencePapers", []))
    skills = "".join(f'<article class="content-entry"><h3>{markdown_inline(group.get("title"))}</h3><p>{"<span class=\"entry-separator\"> · </span>".join(markdown_inline(item.get("name")) for item in group.get("items", []))}</p></article>' for group in portfolio.tech_stack)
    name = markdown_inline(profile.get("name", portfolio.author))
    summary = markdown_inline(profile.get("summary", ""))
    cv_title_source = f"CV - {localized(portfolio.site_name)}"
    cv_title = markdown_text(cv_title_source)
    metadata = _metadata(
        title=cv_title_source,
        description=f"CV and academic profile by {localized(portfolio.author)}.",
        canonical_path="pages/cv.html",
        og_type="profile",
        image_path="assets/images/Avatar.jpg",
    )
    return f'''<!DOCTYPE html>
{MARKER}
<html lang="en" data-theme="dark"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{cv_title}</title>{metadata}{favicon}<script>document.documentElement.setAttribute('data-theme', localStorage.getItem('theme') || 'dark');</script><link rel="stylesheet" href="../assets/css/style.css"></head>
<body data-page="resume">{_nav(portfolio, "../", active_cv=True)}<main class="section-padding"><div class="container resume-page"><a class="back-link" href="../index.html">&lt; <span data-i18n="resume.back">Back to Home</span></a><h1 data-i18n="resume.title">CV</h1><div class="resume-layout"><aside class="resume-sidebar"><div class="resume-profile-heading"><div class="resume-avatar-wrap"><div class="avatar-glow" aria-hidden="true"></div><img tabindex="0" class="resume-profile-avatar" src="../assets/images/Avatar.jpg" alt="{markdown_text(profile.get("name", portfolio.author))} profile portrait"></div><div class="resume-profile-identity"><h2 class="resume-profile-name">{name}</h2><div class="resume-download">{_download(portfolio.resume, "../")}</div></div></div><div class="resume-profile-details"><p>{summary}</p></div><div class="contact-links resume-contact-links" aria-label="Contact links">{_contacts(portfolio, "../")}</div></aside><div class="resume-main">
<section class="narrative-container"><h2 data-i18n="education.title">Education</h2><div class="content-list resume-education">{education}</div></section><section class="narrative-container"><h2 data-i18n="work.title">Work Experience</h2><div class="content-list resume-work">{work}</div></section><section class="narrative-container"><h2 data-i18n="publications.title">Publications</h2><h3 data-i18n="publications.journal">Journal Articles</h3><div class="content-list resume-journals">{journals}</div><h3 data-i18n="publications.conference">Conference Papers</h3><div class="content-list resume-conferences">{conferences}</div></section><section class="narrative-container"><h2 data-i18n="skills.title">Tech Stack</h2><div class="content-list resume-skills">{skills}</div></section><section class="narrative-container"><h2 data-i18n="awards.title">Awards &amp; Scholarships</h2><div class="content-list resume-awards">{awards}</div></section></div></div></div></main>{_footer(portfolio)}<script type="module" src="../assets/js/resume.js"></script></body></html>'''
LINK_PRESENTATION = {
    "github": ("github", "Code"),
    "techDoc": ("file-pdf", "Docs"),
    "bilibili": ("bilibili", "Bilibili"),
    "youtube": ("youtube", "YouTube"),
}


def _project_blocks(blocks: list[dict[str, Any]]) -> str:
    parts: list[str] = []
    for block in blocks:
        kind = block.get("type")
        if kind == "heading":
            level = min(6, max(2, int(block.get("level", 2))))
            parts.append(f'<h{level}>{markdown_inline(block.get("text"))}</h{level}>')
        elif kind == "paragraph":
            parts.append(f'<div class="project-detail-desc markdown-body">{markdown_block(block.get("text"))}</div>')
        elif kind == "image":
            caption = f'<figcaption>{markdown_inline(block.get("caption"))}</figcaption>' if block.get("caption") else ""
            parts.append(f'<figure><img class="project-img" src="../../{escape(str(block.get("src", "")), quote=True)}" alt="{markdown_text(block.get("alt"))}" loading="lazy" decoding="async">{caption}</figure>')
        elif kind == "gallery":
            figures = []
            for image in block.get("images", []):
                caption = f'<figcaption>{markdown_inline(image.get("caption"))}</figcaption>' if image.get("caption") else ""
                figures.append(f'<figure><img class="project-img" src="../../{escape(str(image.get("src", "")), quote=True)}" alt="{markdown_text(image.get("alt"))}" loading="lazy">{caption}</figure>')
            parts.append('<div class="project-gallery">' + "".join(figures) + "</div>")
        elif kind == "list":
            tag = "ol" if block.get("ordered") else "ul"
            parts.append(f'<{tag}>' + "".join(f'<li>{markdown_inline(item)}</li>' for item in block.get("items", [])) + f'</{tag}>')
        elif kind == "quote":
            source = f'<cite>{markdown_inline(block.get("source"))}</cite>' if block.get("source") else ""
            parts.append(f'<blockquote>{markdown_block(block.get("text"))}{source}</blockquote>')
        elif kind == "metrics":
            values = "".join(f'<dt>{markdown_inline(item.get("label"))}</dt><dd>{markdown_inline(item.get("value"))}</dd>' for item in block.get("items", []))
            parts.append(f'<dl class="project-metrics">{values}</dl>')
        elif kind == "video" and str(block.get("url", "")).startswith("https://"):
            parts.append(f'<a href="{escape(str(block["url"]), quote=True)}" target="_blank" rel="noopener noreferrer">{markdown_inline(block.get("title") or block["url"])}</a>')
    return "".join(parts)


def render_project(portfolio: Any, project: dict[str, Any]) -> str:
    content = project["locales"]["en"]
    visible = [item for item in portfolio.projects if item.get("status") != "draft"]
    position = next((index for index, item in enumerate(visible) if item.get("id") == project.get("id")), -1)
    adjacent = []
    if position > 0:
        previous = visible[position - 1]
        adjacent.append(f'<a class="project-adjacent-link previous" href="../../{escape(str(previous["page"]), quote=True)}"><span class="project-adjacent-label">&lt; Previous</span><span class="project-adjacent-name">{markdown_inline(previous["locales"]["en"]["title"])}</span></a>')
    if 0 <= position < len(visible) - 1:
        following = visible[position + 1]
        adjacent.append(f'<a class="project-adjacent-link next" href="../../{escape(str(following["page"]), quote=True)}"><span class="project-adjacent-label">Next &gt;</span><span class="project-adjacent-name">{markdown_inline(following["locales"]["en"]["title"])}</span></a>')
    links = []
    for link in project.get("links", []):
        presentation = LINK_PRESENTATION.get(str(link.get("type")))
        if not presentation or not str(link.get("url", "")).startswith("https://"):
            continue
        icon, default_label = presentation
        label = markdown_inline(link.get("label") or default_label)
        links.append(f'<a class="publish-link" href="{escape(str(link["url"]), quote=True)}" target="_blank" rel="noopener noreferrer">{_icon(icon)}<span>{label}</span></a>')
    links_html = '<div class="publish-links-wrapper"><div class="publish-links">' + "".join(links) + "</div></div>" if links else ""
    favicon = _favicon(portfolio.favicon, "../../")
    robots = '<meta name="robots" content="noindex, nofollow">' if project.get("status") == "draft" else ""
    page_title_source = f'{localized(content.get("title"))} - {localized(portfolio.site_name)}'
    page_title = markdown_text(page_title_source)
    metadata = _metadata(
        title=page_title_source,
        description=content.get("summary", ""),
        canonical_path=str(project.get("page", "")),
        og_type="article",
        image_path=str(project.get("thumbnail", {}).get("src", "")) or None,
        structured_data={
            "@context": "https://schema.org",
            "@type": "CreativeWork",
            "name": markdown_plain(content.get("title")),
            "description": markdown_plain(content.get("summary")),
            "url": f'{SITE_ORIGIN}/{project.get("page", "")}',
        },
    )
    return f'''<!DOCTYPE html>
{MARKER}
<html lang="en" data-theme="dark"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{page_title}</title>{robots}{metadata}{favicon}<script>document.documentElement.setAttribute('data-theme', localStorage.getItem('theme') || 'dark');</script><link rel="stylesheet" href="../../assets/css/style.css"></head><body data-page="project" data-project-id="{escape(str(project.get("id")), quote=True)}">{_nav(portfolio, "../../")}<main class="section-padding"><div class="container"><div class="card project-detail-card"><div class="project-container"><a class="back-link" href="../../index.html#projects">&lt; Back to Projects</a><h2>{markdown_inline(content.get("title"))}</h2>{_project_blocks(content.get("blocks", []))}{links_html}<nav class="project-adjacent" aria-label="Project navigation">{"".join(adjacent)}</nav></div></div></div></main>{_footer(portfolio)}<script type="module" src="../../assets/js/app.js"></script></body></html>'''


def write_text_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False, newline="\n") as handle:
        handle.write(content + "\n")
        temporary = Path(handle.name)
    os.replace(temporary, path)
