from __future__ import annotations

from calendar import month_abbr
from datetime import date as Date
from html import escape, unescape
from pathlib import Path
from typing import Any
import json
import os
import posixpath
import re
import tempfile

from .vendor import markdown2


MARKER = "<!-- Generated by portfolio.py; do not edit. -->"
SITE_ORIGIN = "https://hancheng-guo.github.io"
_UNDERLINE = re.compile(r"(?<![\w_])_(?!_)(?=\S)([^_\n]*?\S)_(?![\w_])")
_UNSAFE_HREF = re.compile(r'\s+href="(?!https?://|mailto:|tel:|#|/|\.\.?/)[^"]*"', re.I)
_VOID_TAGS = {"area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "source", "track", "wbr"}
_RAW_TAGS = {"script", "style", "pre", "code", "textarea"}
_INLINE_TAGS = {"a", "abbr", "b", "br", "cite", "code", "em", "i", "mark", "small", "span", "strong", "sub", "sup", "time", "u"}
_SIMPLE_TEXT_TAGS = {"title", "h1", "h2", "h3", "h4", "h5", "h6", "p", "dt", "dd", "figcaption", "li"}


def _tag_end(source: str, start: int) -> int:
    """Return the end of an HTML tag while respecting quoted attributes."""
    quote: str | None = None
    index = start + 1
    while index < len(source):
        char = source[index]
        if quote:
            if char == quote:
                quote = None
        elif char in {"'", '"'}:
            quote = char
        elif char == ">":
            return index + 1
        index += 1
    return len(source)


def _tag_name(token: str) -> str | None:
    match = re.match(r"<\s*/?\s*([a-zA-Z][\w:-]*)", token)
    return match.group(1).lower() if match else None


def _html_tree(document: str) -> list[dict[str, Any]]:
    """Parse only the small HTML subset emitted by this generator, losslessly."""
    root: list[dict[str, Any]] = []
    stack: list[dict[str, Any]] = []

    def append(node: dict[str, Any]) -> None:
        (stack[-1]["children"] if stack else root).append(node)

    index = 0
    while index < len(document):
        if document[index] != "<":
            next_tag = document.find("<", index)
            next_tag = len(document) if next_tag < 0 else next_tag
            append({"kind": "text", "value": document[index:next_tag]})
            index = next_tag
            continue
        if document.startswith("<!--", index):
            end = document.find("-->", index + 4)
            end = len(document) if end < 0 else end + 3
            append({"kind": "raw", "value": document[index:end]})
            index = end
            continue
        end = _tag_end(document, index)
        token = document[index:end]
        name = _tag_name(token)
        if not name:
            append({"kind": "raw", "value": token})
            index = end
            continue
        if token.startswith("</"):
            if stack and stack[-1]["name"] == name:
                stack[-1]["close"] = token
                stack.pop()
            else:
                append({"kind": "raw", "value": token})
            index = end
            continue
        if name in _RAW_TAGS:
            close_match = re.search(rf"</\s*{re.escape(name)}\s*>", document[end:], re.I)
            raw_end = end + close_match.end() if close_match else len(document)
            append({"kind": "raw", "value": document[index:raw_end]})
            index = raw_end
            continue
        node = {"kind": "tag", "name": name, "open": token, "close": "", "children": []}
        append(node)
        if name not in _VOID_TAGS and not token.rstrip().endswith("/>"):
            stack.append(node)
        index = end
    return root


def pretty_html(document: str) -> str:
    """Format generated HTML using a quote-aware, lossless token tree.

    It deliberately never rewrites text nodes or raw script/style/pre/code
    payloads, so Markdown inline content and JavaScript/CSS whitespace retain
    their original semantics.
    """
    def inline(node: dict[str, Any]) -> str | None:
        if node["kind"] == "raw":
            return node["value"] if "\n" not in node["value"] else None
        if node["kind"] == "text":
            return node["value"] if "\n" not in node["value"] else None
        pieces: list[str] = []
        for child in node["children"]:
            piece = inline(child)
            if piece is None:
                return None
            pieces.append(piece)
        if node["name"] in _INLINE_TAGS or node["name"] in _SIMPLE_TEXT_TAGS:
            return node["open"] + "".join(pieces) + node["close"]
        return None

    lines: list[str] = []
    def render(node: dict[str, Any], depth: int) -> None:
        prefix = "  " * depth
        compact = inline(node)
        if compact is not None:
            lines.append(prefix + compact)
            return
        if node["kind"] == "raw":
            if node["value"].strip():
                lines.append(prefix + node["value"])
            return
        if node["kind"] == "text":
            # Newlines in normal HTML text collapse to whitespace in the
            # browser.  Split them only to avoid formatter-created blank lines
            # with trailing indentation; raw/pre/code payloads bypass this.
            for piece in node["value"].splitlines():
                if piece.strip():
                    lines.append(prefix + piece.strip())
            return
        lines.append(prefix + node["open"])
        for child in node["children"]:
            if child["kind"] == "text" and not child["value"].strip():
                continue
            render(child, depth + 1)
        if node["close"]:
            lines.append(prefix + node["close"])

    for node in _html_tree(document):
        if node["kind"] == "text" and not node["value"].strip():
            continue
        render(node, 0)
    return "\n".join(line.rstrip() for line in lines).strip()


def localized(value: Any, language: str = "en") -> Any:
    if isinstance(value, dict) and ("en" in value or "zh" in value):
        return value.get(language, value.get("en", ""))
    return value


def _prepare_markdown(value: Any) -> str:
    text = str(localized(value) or "")
    return _UNDERLINE.sub(lambda match: f"MDUNDERLINEOPEN{match.group(1)}MDUNDERLINECLOSE", text)


def markdown_block(value: Any) -> str:
    rendered = str(markdown2.markdown(
        _prepare_markdown(value),
        safe_mode="escape",
        extras=["break-on-newline", "cuddled-lists", "fenced-code-blocks", "strike", "tables"],
    ))
    rendered = rendered.replace("MDUNDERLINEOPEN", "<u>").replace("MDUNDERLINECLOSE", "</u>")
    return _UNSAFE_HREF.sub("", rendered).strip()


def markdown_inline(value: Any) -> str:
    rendered = markdown_block(value)
    if rendered.startswith("<p>") and rendered.endswith("</p>") and rendered.count("<p>") == 1:
        return rendered[3:-4].rstrip("\n")
    return rendered


def markdown_plain(value: Any) -> str:
    return unescape(re.sub(r"<[^>]+>", "", markdown_inline(value)))


def markdown_text(value: Any) -> str:
    return escape(markdown_plain(value), quote=True)


def format_month(value: str, language: str = "en") -> str:
    year, month = (int(part) for part in value.split("-"))
    return f"{year}年{month}月" if language == "zh" else f"{month_abbr[month]} {year}"


def format_date_range(value: Any, language: str = "en") -> str:
    if not value:
        return ""
    if isinstance(value, str):
        start, end = value, None
    else:
        start, end = value.get("start"), value.get("end")
    if not start:
        return ""
    if isinstance(value, dict) and not end:
        month = format_month(start, language)
        return f"{start[:4]}年{int(start[5:])}月 至今" if language == "zh" else f"Since {month}"
    start_text = format_month(start, language)
    return f"{start_text} – {format_month(end, language)}" if end and end != start else start_text


def format_full_date(value: str, language: str = "en") -> str:
    parsed = Date.fromisoformat(value)
    return f"{parsed.year}年{parsed.month}月{parsed.day}日" if language == "zh" else f"{month_abbr[parsed.month]} {parsed.day}, {parsed.year}"


def _icon(name: str) -> str:
    safe_name = re.sub(r"[^a-z0-9-]", "", name.lower())
    # Keep the generated document useful when it is opened directly from disk.
    # Chromium-family browsers block external SVGs used as CSS masks for a
    # ``file://`` document, which used to make every static control glyph
    # disappear.  These are first-party, allow-listed assets, so embed their
    # SVG markup in generated HTML; hydrated pages may still use the compact
    # CSS-mask spans created by JavaScript over HTTP.
    icon_path = Path(__file__).resolve().parents[1] / "assets" / "icons" / f"{safe_name}.svg"
    try:
        markup = icon_path.read_text(encoding="utf-8").strip()
    except OSError:
        return f'<span class="svg-icon icon-{safe_name}" aria-hidden="true"></span>'
    svg_start = re.search(r"<svg\b", markup)
    if not svg_start:
        return f'<span class="svg-icon icon-{safe_name}" aria-hidden="true"></span>'
    # Some local SVGs contain an XML declaration or repository comments.
    # Generated pages are HTML documents, so embed the SVG element only.
    markup = markup[svg_start.start():]
    return re.sub(
        r"<svg\b",
        f'<svg class="svg-icon svg-icon--inline icon-{safe_name}" aria-hidden="true" focusable="false"',
        markup,
        count=1,
    )


def _favicon(path: str | None, prefix: str) -> str:
    return f'  <link rel="icon" href="{prefix}{escape(path, quote=True)}">\n' if path else ""


def _metadata(
    *,
    title: Any,
    description: Any,
    canonical_path: str,
    og_type: str,
    image_path: str | None = None,
    structured_data: dict[str, Any] | None = None,
) -> str:
    safe_title = markdown_text(title)
    safe_description = markdown_text(description)
    canonical = f"{SITE_ORIGIN}/{canonical_path.lstrip('/')}" if canonical_path else f"{SITE_ORIGIN}/"
    image = f'<meta property="og:image" content="{SITE_ORIGIN}/{escape(image_path, quote=True)}">' if image_path else ""
    structured = ""
    if structured_data:
        payload = json.dumps(structured_data, ensure_ascii=False, separators=(",", ":")).replace("<", "\\u003c")
        structured = f'<script type="application/ld+json">{payload}</script>'
    return f'''<meta name="description" content="{safe_description}">
<meta property="og:title" content="{safe_title}">
<meta property="og:description" content="{safe_description}">
<meta property="og:type" content="{escape(og_type, quote=True)}">
<meta property="og:url" content="{canonical}">
{image}<link rel="canonical" href="{canonical}">
{structured}'''


def _theme_button() -> str:
    return '<button class="control-btn nav-control theme-toggle" type="button" aria-label="Toggle color theme" data-i18n-aria-label="nav.toggleTheme">' + _icon("sun").replace('class="svg-icon', 'class="svg-icon sun-icon') + _icon("moon").replace('class="svg-icon', 'class="svg-icon moon-icon') + "</button>"


def _anchor_bootstrap() -> str:
    """Hide a cross-document non-top fragment until its static target is ready.

    This is deliberately inline and precedes the stylesheet: the browser can
    perform its native fragment scroll during parsing without ever exposing a
    top-of-page frame.  The timeout is a no-JS-error safety net.
    """
    return '''<style>html[data-anchor-pending] body{opacity:0}html[data-anchor-pending].anchor-ready body{opacity:1;transition:opacity .14s ease}</style><script>(function(){var r=document.documentElement,h=location.hash;if(!h||h==='#top'||(matchMedia&&matchMedia('(prefers-reduced-motion: reduce)').matches))return;r.dataset.anchorPending='true';setTimeout(function(){r.classList.add('anchor-ready')},350)})()</script>'''


def _nav(portfolio: Any, prefix: str, *, active_cv: bool = False) -> str:
    author = markdown_inline(portfolio.author)
    home = f"{prefix}index.html"
    cv = f"{prefix}pages/cv.html"
    active = ' class="active"' if active_cv else ""
    visible_projects = [project for project in portfolio.projects if project.get("status") != "draft"]
    publications = portfolio.publications
    visible_journals = [item for item in publications.get("journalArticles", []) if item.get("status") != "draft"]
    visible_conferences = [item for item in publications.get("conferencePapers", []) if item.get("status") != "draft"]
    visible_timeline = [item for item in portfolio.timeline if item.get("status") != "draft"]
    section_links = [f'<a href="{home}#profile" data-i18n="nav.profile">Profile</a>']
    if visible_projects:
        section_links.append(f'<a href="{home}#projects" data-i18n="nav.project">Project</a>')
    if visible_journals or visible_conferences:
        section_links.append(f'<a href="{home}#publications" data-i18n="nav.publications">Publications</a>')
    if visible_timeline:
        section_links.append(f'<a href="{home}#timeline" data-i18n="nav.timeline">Timeline</a>')
    return f'''<nav><div class="container nav-container">
  <a href="{home}" class="logo"><span class="logo-text">{author}</span><div class="logo-dot"></div></a>
  <div class="nav-actions"><button class="control-btn menu-toggle" type="button" aria-expanded="false" aria-controls="primary-navigation" aria-label="Open navigation" data-i18n-aria-label="nav.openMenu">☰</button>
    <div class="nav-links" id="primary-navigation">{"".join(section_links)}<a href="{cv}"{active} data-i18n="nav.resume">CV</a></div>
    <div class="nav-controls"><button class="control-btn nav-control lang-toggle" type="button" aria-label="切换到中文" title="切换到中文" data-language="en" data-i18n-aria-label="nav.toggleLanguage"><img class="language-target-icon" src="{prefix}assets/icons/language-switch-ch.svg" alt="" aria-hidden="true"><span class="visually-hidden">切换到中文</span></button>{_theme_button()}</div>
  </div>
</div></nav>'''


def _footer(portfolio: Any) -> str:
    author = markdown_inline(portfolio.author)
    copyright_text = markdown_inline(portfolio.copyright_text)
    suffix = f", {copyright_text}" if copyright_text else ""
    updated = format_full_date(portfolio.last_update_date)
    return f'<footer><span class="footer-copyright">© {portfolio.last_update_date[:4]} {author}{suffix}</span><span class="footer-updated">Site last updated {updated}</span></footer>'


def _download(resume: dict[str, Any], prefix: str) -> str:
    url = localized(resume.get("url"))
    if not url:
        return ""
    external = str(url).startswith(("http://", "https://"))
    href = str(url) if external else prefix + str(url)
    attrs = ' target="_blank" rel="noopener noreferrer"' if external else (' download' if resume.get("download", True) else "")
    label = markdown_inline(resume.get("label") or "Download CV")
    return f'<a class="publish-link primary-action" href="{escape(href, quote=True)}"{attrs}>{_icon("file-pdf")}<span>{label}</span></a>'


def _contacts(portfolio: Any, prefix: str = "") -> str:
    parts: list[str] = []
    email = localized(portfolio.profile.get("email"))
    if email:
        safe_email = escape(str(email), quote=True)
        parts.append(f'<div class="contact-item email-contact-item"><a class="email-contact-link" href="mailto:{safe_email}" aria-label="{safe_email}">{_icon("envelope")}<span>{escape(str(email))}</span></a></div>')
    social = []
    for contact in portfolio.contacts:
        label = markdown_inline(contact.get("label"))
        plain_label = markdown_text(contact.get("label"))
        social.append(f'<div class="contact-item"><a href="{escape(str(contact.get("url", "")), quote=True)}" aria-label="{plain_label}" title="{plain_label}" target="_blank" rel="noopener noreferrer">{_icon(str(contact.get("icon", "")))}<span class="visually-hidden">{label}</span></a></div>')
    if social:
        parts.append('<div class="social-contact-group">' + "".join(social) + "</div>")
    return "".join(parts)


def _entry(entry: dict[str, Any], title_field: str, detail_fields: tuple[str, ...]) -> str:
    title = markdown_inline(entry.get(title_field, ""))
    date_text = format_date_range(entry.get("date"))
    details = [markdown_inline(entry.get(field, "")) for field in detail_fields if localized(entry.get(field, ""))]
    pieces: list[str] = []
    if date_text:
        pieces.append(f'<time class="entry-date">{escape(date_text)}</time>')
    pieces.extend(f'<span class="entry-detail">{detail}</span>' for detail in details)
    detail_html = '<span class="entry-separator"> · </span>'.join(pieces)
    details = f'<p>{detail_html}</p>' if detail_html else ""
    return f'<article class="content-entry"><h3>{title}</h3>{details}</article>'


def _publication_entries(items: list[dict[str, Any]]) -> str:
    return "".join(_entry(item, "title", ("venue",)) for item in items)


def _education_entry(entry: dict[str, Any]) -> str:
    """Render the intentional three-line Education CV format.

    Accept legacy raw entries as well as the canonical fields emitted by the
    current builder. This matters for users who retained an older site.json.
    """
    position = entry.get("position") or entry.get("degree") or entry.get("institution") or ""
    institute = entry.get("institute") or entry.get("institution") or ""
    location = entry.get("location") or ""
    detail = entry.get("detail") or ""
    first_line = f'<strong>{markdown_inline(position)}</strong>'
    place = [markdown_inline(value) for value in (institute, location) if localized(value)]
    if place:
        first_line += ", " + ", ".join(place)
    date_text = format_date_range(entry.get("date"))
    date_line = f'<time class="entry-date">{escape(date_text)}</time>' if date_text else ""
    detail_line = f'<p class="education-detail">{markdown_inline(detail)}</p>' if localized(detail) else ""
    return f'<article class="content-entry education-entry"><h3 class="education-heading">{first_line}</h3>{date_line}{detail_line}</article>'


def _work_entry(entry: dict[str, Any]) -> str:
    """Render Work Experience in the same three-line layout as Education."""
    position = entry.get("position") or ""
    company = entry.get("company") or ""
    location = entry.get("location") or ""
    detail = entry.get("detail") or ""
    first_line = f'<strong>{markdown_inline(position)}</strong>'
    place = [markdown_inline(value) for value in (company, location) if localized(value)]
    if place:
        first_line += ", " + ", ".join(place)
    date_text = format_date_range(entry.get("date"))
    date_line = f'<time class="entry-date">{escape(date_text)}</time>' if date_text else ""
    detail_line = f'<p class="work-detail">{markdown_inline(detail)}</p>' if localized(detail) else ""
    return f'<article class="content-entry work-entry"><h3 class="work-heading">{first_line}</h3>{date_line}{detail_line}</article>'


def _profile_asset(profile: dict[str, Any], key: str) -> str | None:
    """Return an explicitly configured profile asset, never a placeholder."""
    value = profile.get(key)
    return value.strip() if isinstance(value, str) and value.strip() else None


def _hero_attributes(hero_background: str | None) -> str:
    if not hero_background:
        return ""
    # This value is consumed by the stylesheet's pseudo-element, so browsers
    # resolve its URL relative to ``assets/css/style.css``.  Translate the
    # configured repository-relative asset path to that base.  A leading site
    # slash would instead break direct file previews and project-site mounts.
    css_path = posixpath.relpath(hero_background.lstrip("/"), start="assets/css")
    css_url = f"url({json.dumps(css_path)})"
    return f' data-hero-background="true" style="--hero-background-image: {escape(css_url, quote=True)}"'


def _project_card(project: dict[str, Any]) -> str:
    content = project["locales"]["en"]
    date_text = format_date_range(project.get("date"))
    tags = "".join(f'<span class="project-tag">{markdown_inline(tag)}</span>' for tag in project.get("tags", []))
    href = escape(str(project["page"]), quote=True)
    image = project.get("thumbnail", {})
    alt = markdown_text(localized(image.get("alt")))
    # The hidden time is deliberately retained for undated projects.  The
    # client renderer uses this exact node too, which prevents hydration from
    # changing the footer's layout or DOM shape.
    date_element = f'<time class="project-date">{escape(date_text)}</time>' if date_text else '<time class="project-date" hidden></time>'
    return f'''<article class="card" tabindex="0" data-project-href="{href}"><div class="project-thumbnail-wrapper"><img class="project-thumbnail" src="{escape(str(image.get("src", "")), quote=True)}" alt="{alt}" loading="lazy" decoding="async"></div><div class="project-info"><div class="project-copy"><h3>{markdown_inline(content.get("title"))}</h3><p class="project-summary">{markdown_inline(content.get("summary"))}</p></div><div class="project-meta"><div class="project-tags">{tags}</div><div class="project-card-footer"><a class="project-link" href="{href}">View Details</a>{date_element}</div></div></div></article>'''


def _timeline(portfolio: Any) -> tuple[str, bool]:
    events = list(reversed([event for event in portfolio.timeline if event.get("status") != "draft"]))
    parts = []
    for index, event in enumerate(events):
        extra = " timeline-extra" if index >= 8 else ""
        parts.append(f'<div class="timeline-item{extra}"><div class="timeline-dot"></div><div class="timeline-summary"><span class="timeline-date">{escape(format_date_range(event.get("date")))}</span><h3>{markdown_inline(event.get("title"))}</h3></div><div class="timeline-content"><p>{markdown_inline(event.get("description"))}</p></div></div>')
    return "".join(parts), len(events) > 8


def render_home(portfolio: Any) -> str:
    profile = portfolio.profile
    avatar = _profile_asset(profile, "avatar")
    hero_background = _profile_asset(profile, "hero_background")
    name = markdown_inline(profile.get("name", portfolio.author))
    summary = markdown_inline(profile.get("summary", ""))
    visible_projects = [project for project in portfolio.projects if project.get("status") != "draft"]
    visible_journals = [item for item in portfolio.publications.get("journalArticles", []) if item.get("status") != "draft"]
    visible_conferences = [item for item in portfolio.publications.get("conferencePapers", []) if item.get("status") != "draft"]
    projects = "".join(_project_card(project) for project in visible_projects)
    journals = _publication_entries(visible_journals)
    conferences = _publication_entries(visible_conferences)
    timeline, has_more = _timeline(portfolio)
    toggle_attrs = "" if has_more else " hidden"
    favicon = _favicon(portfolio.favicon, "")
    title = markdown_text(portfolio.site_name)
    metadata = _metadata(
        title=portfolio.site_name,
        description=profile.get("summary", ""),
        canonical_path="",
        og_type="website",
        image_path=avatar,
        structured_data={
            "@context": "https://schema.org",
            "@type": "Person",
            "name": markdown_plain(profile.get("name", portfolio.author)),
            "url": f"{SITE_ORIGIN}/",
        },
    )
    project_section = f'<section id="projects" class="section-padding"><div class="container"><h2 data-i18n="projects.title">Projects</h2><div class="projects-grid">{projects}</div></div></section>' if visible_projects else ""
    publication_categories = ""
    if visible_journals:
        publication_categories += f'<h3 data-i18n="publications.journal">Journal Articles</h3><div class="content-list home-journals">{journals}</div>'
    if visible_conferences:
        publication_categories += f'<h3 data-i18n="publications.conference">Conference Papers</h3><div class="content-list home-conferences">{conferences}</div>'
    publication_section = f'<section id="publications" class="section-padding"><div class="container"><h2 data-i18n="publications.title">Publications</h2><div class="narrative-container">{publication_categories}</div></div></section>' if publication_categories else ""
    timeline_section = f'<section id="timeline" class="section-padding"><div class="container"><h2 data-i18n="timeline.title">Timeline</h2><div class="timeline-container">{timeline}</div><button class="control-btn timeline-toggle" type="button" aria-expanded="false"{toggle_attrs}><span class="timeline-toggle-label" data-i18n="timeline.showMore">Show more</span>{_icon("chevron-down").replace("class=\"svg-icon", "class=\"svg-icon timeline-chevron")}</button></div></section>' if timeline else ""
    profile_decoration = '<div class="bg-decoration" aria-hidden="true"></div>' if avatar else ""
    return f'''<!DOCTYPE html>
{MARKER}
<html lang="en" data-theme="dark"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{title}</title>{metadata}{favicon}<script>document.documentElement.setAttribute('data-theme', localStorage.getItem('theme') || 'dark');</script>{_anchor_bootstrap()}<link rel="stylesheet" href="assets/css/style.css"></head>
<body id="top" data-page="home">{_nav(portfolio, "")}
<main><section id="profile" class="intro profile-section"{_hero_attributes(hero_background)}>{profile_decoration}<div class="container flex-center column">{f'<div class="avatar-container"><div class="avatar-glow"></div><img class="avatar" src="{escape(avatar, quote=True)}" alt="{markdown_text(profile.get("name", portfolio.author))} profile portrait"></div>' if avatar else ''}<h1 class="gradient-text hero-title">Hello, I'm {name}</h1><div class="subtitle hero-summary">{summary}</div><div class="hero-action-row"><div class="intro-actions">{_download(portfolio.resume, "")}</div><div id="contact" class="contact-links hero-contact-links" aria-label="Contact links">{_contacts(portfolio)}</div></div></div></section>{project_section}{publication_section}{timeline_section}</main>
{_footer(portfolio)}<script type="module" src="assets/js/app.js"></script></body></html>'''


def render_cv(portfolio: Any) -> str:
    profile = portfolio.profile
    avatar = _profile_asset(profile, "avatar")
    favicon = _favicon(portfolio.favicon, "../")
    education_items = [item for item in portfolio.education if item.get("status") != "draft"]
    work_items = [item for item in portfolio.work_experience if item.get("status") != "draft"]
    award_items = [item for item in portfolio.awards if item.get("status") != "draft"]
    skill_groups = [group for group in portfolio.tech_stack if group.get("status") != "draft"]
    journal_items = [item for item in portfolio.publications.get("journalArticles", []) if item.get("status") != "draft"]
    conference_items = [item for item in portfolio.publications.get("conferencePapers", []) if item.get("status") != "draft"]
    education = "".join(_education_entry(item) for item in education_items)
    work = "".join(_work_entry(item) for item in work_items)
    awards = "".join(_entry(item, "title", ()) for item in award_items)
    journals = _publication_entries(journal_items)
    conferences = _publication_entries(conference_items)
    skills = "".join(f'<article class="content-entry"><h3>{markdown_inline(group.get("title"))}</h3><p>{"<span class=\"entry-separator\"> · </span>".join(markdown_inline(item.get("name")) for item in group.get("items", []))}</p></article>' for group in skill_groups)
    education_section = f'<section class="narrative-container"><h2 data-i18n="education.title">Education</h2><div class="content-list resume-education">{education}</div></section>' if education else ""
    work_section = f'<section class="narrative-container"><h2 data-i18n="work.title">Work Experience</h2><div class="content-list resume-work">{work}</div></section>' if work else ""
    publication_categories = ""
    if journals:
        publication_categories += f'<h3 data-i18n="publications.journal">Journal Articles</h3><div class="content-list resume-journals">{journals}</div>'
    if conferences:
        publication_categories += f'<h3 data-i18n="publications.conference">Conference Papers</h3><div class="content-list resume-conferences">{conferences}</div>'
    publications_section = f'<section class="narrative-container"><h2 data-i18n="publications.title">Publications</h2>{publication_categories}</section>' if publication_categories else ""
    skills_section = f'<section class="narrative-container"><h2 data-i18n="skills.title">Tech Stack</h2><div class="content-list resume-skills">{skills}</div></section>' if skills else ""
    awards_section = f'<section class="narrative-container"><h2 data-i18n="awards.title">Awards &amp; Scholarships</h2><div class="content-list resume-awards">{awards}</div></section>' if awards else ""
    name = markdown_inline(profile.get("name", portfolio.author))
    summary = markdown_inline(profile.get("summary", ""))
    cv_title_source = f"CV - {localized(portfolio.site_name)}"
    cv_title = markdown_text(cv_title_source)
    metadata = _metadata(
        title=cv_title_source,
        description=f"CV and academic profile by {localized(portfolio.author)}.",
        canonical_path="pages/cv.html",
        og_type="profile",
        image_path=avatar,
    )
    return f'''<!DOCTYPE html>
{MARKER}
<html lang="en" data-theme="dark"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{cv_title}</title>{metadata}{favicon}<script>document.documentElement.setAttribute('data-theme', localStorage.getItem('theme') || 'dark');</script><link rel="stylesheet" href="../assets/css/style.css"></head>
<body data-page="resume">{_nav(portfolio, "../", active_cv=True)}<main class="section-padding"><div class="container resume-page"><a class="back-link" href="../index.html">&lt; <span data-i18n="resume.back">Back to Home</span></a><h1 data-i18n="resume.title">CV</h1><div class="resume-layout"><aside class="resume-sidebar"><div class="resume-profile-heading">{f'<div class="resume-avatar-wrap"><div class="avatar-glow" aria-hidden="true"></div><img tabindex="0" class="resume-profile-avatar" src="../{escape(avatar, quote=True)}" alt="{markdown_text(profile.get("name", portfolio.author))} profile portrait"></div>' if avatar else ''}<div class="resume-profile-identity"><h2 class="resume-profile-name">{name}</h2><div class="resume-download">{_download(portfolio.resume, "../")}</div></div></div><div class="resume-profile-details"><p>{summary}</p></div><div class="contact-links resume-contact-links" aria-label="Contact links">{_contacts(portfolio, "../")}</div></aside><div class="resume-main">
{education_section}{work_section}{publications_section}{skills_section}{awards_section}</div></div></div></main>{_footer(portfolio)}<script type="module" src="../assets/js/resume.js"></script></body></html>'''
LINK_PRESENTATION = {
    "github": ("github", "Code"),
    "techDoc": ("file-pdf", "Docs"),
    "bilibili": ("bilibili", "Bilibili"),
    "youtube": ("youtube", "YouTube"),
}


def _project_blocks(blocks: list[dict[str, Any]]) -> str:
    parts: list[str] = []
    for block in blocks:
        kind = block.get("type")
        if kind == "heading":
            level = min(6, max(2, int(block.get("level", 2))))
            parts.append(f'<h{level}>{markdown_inline(block.get("text"))}</h{level}>')
        elif kind == "paragraph":
            parts.append(f'<div class="project-detail-desc markdown-body">{markdown_block(block.get("text"))}</div>')
        elif kind == "image":
            caption = f'<figcaption>{markdown_inline(block.get("caption"))}</figcaption>' if block.get("caption") else ""
            parts.append(f'<figure><img class="project-img" src="../../{escape(str(block.get("src", "")), quote=True)}" alt="{markdown_text(block.get("alt"))}" loading="lazy" decoding="async">{caption}</figure>')
        elif kind == "gallery":
            figures = []
            for image in block.get("images", []):
                caption = f'<figcaption>{markdown_inline(image.get("caption"))}</figcaption>' if image.get("caption") else ""
                figures.append(f'<figure><img class="project-img" src="../../{escape(str(image.get("src", "")), quote=True)}" alt="{markdown_text(image.get("alt"))}" loading="lazy">{caption}</figure>')
            parts.append('<div class="project-gallery">' + "".join(figures) + "</div>")
        elif kind == "list":
            tag = "ol" if block.get("ordered") else "ul"
            parts.append(f'<{tag}>' + "".join(f'<li>{markdown_inline(item)}</li>' for item in block.get("items", [])) + f'</{tag}>')
        elif kind == "quote":
            source = f'<cite>{markdown_inline(block.get("source"))}</cite>' if block.get("source") else ""
            parts.append(f'<blockquote>{markdown_block(block.get("text"))}{source}</blockquote>')
        elif kind == "metrics":
            values = "".join(f'<dt>{markdown_inline(item.get("label"))}</dt><dd>{markdown_inline(item.get("value"))}</dd>' for item in block.get("items", []))
            parts.append(f'<dl class="project-metrics">{values}</dl>')
        elif kind == "video" and str(block.get("url", "")).startswith("https://"):
            parts.append(f'<a href="{escape(str(block["url"]), quote=True)}" target="_blank" rel="noopener noreferrer">{markdown_inline(block.get("title") or block["url"])}</a>')
    return "".join(parts)


def render_project(portfolio: Any, project: dict[str, Any]) -> str:
    content = project["locales"]["en"]
    visible = [item for item in portfolio.projects if item.get("status") != "draft"]
    position = next((index for index, item in enumerate(visible) if item.get("id") == project.get("id")), -1)
    adjacent = []
    if position > 0:
        previous = visible[position - 1]
        adjacent.append(f'<a class="project-adjacent-link previous" href="../../{escape(str(previous["page"]), quote=True)}"><span class="project-adjacent-label">&lt; Previous</span><span class="project-adjacent-name">{markdown_inline(previous["locales"]["en"]["title"])}</span></a>')
    if 0 <= position < len(visible) - 1:
        following = visible[position + 1]
        adjacent.append(f'<a class="project-adjacent-link next" href="../../{escape(str(following["page"]), quote=True)}"><span class="project-adjacent-label">Next &gt;</span><span class="project-adjacent-name">{markdown_inline(following["locales"]["en"]["title"])}</span></a>')
    links = []
    for link in project.get("links", []):
        presentation = LINK_PRESENTATION.get(str(link.get("type")))
        if not presentation or not str(link.get("url", "")).startswith("https://"):
            continue
        icon, default_label = presentation
        label = markdown_inline(link.get("label") or default_label)
        links.append(f'<a class="publish-link" href="{escape(str(link["url"]), quote=True)}" target="_blank" rel="noopener noreferrer">{_icon(icon)}<span>{label}</span></a>')
    links_html = '<div class="publish-links-wrapper"><div class="publish-links">' + "".join(links) + "</div></div>" if links else ""
    favicon = _favicon(portfolio.favicon, "../../")
    robots = '<meta name="robots" content="noindex, nofollow">' if project.get("status") == "draft" else ""
    page_title_source = f'{localized(content.get("title"))} - {localized(portfolio.site_name)}'
    page_title = markdown_text(page_title_source)
    metadata = _metadata(
        title=page_title_source,
        description=content.get("summary", ""),
        canonical_path=str(project.get("page", "")),
        og_type="article",
        image_path=str(project.get("thumbnail", {}).get("src", "")) or None,
        structured_data={
            "@context": "https://schema.org",
            "@type": "CreativeWork",
            "name": markdown_plain(content.get("title")),
            "description": markdown_plain(content.get("summary")),
            "url": f'{SITE_ORIGIN}/{project.get("page", "")}',
        },
    )
    return f'''<!DOCTYPE html>
{MARKER}
<html lang="en" data-theme="dark"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{page_title}</title>{robots}{metadata}{favicon}<script>document.documentElement.setAttribute('data-theme', localStorage.getItem('theme') || 'dark');</script><link rel="stylesheet" href="../../assets/css/style.css"></head><body data-page="project" data-project-id="{escape(str(project.get("id")), quote=True)}">{_nav(portfolio, "../../")}<main class="section-padding"><div class="container"><div class="card project-detail-card"><div class="project-container"><a class="back-link" href="../../index.html#projects">&lt; Back to Projects</a><h2>{markdown_inline(content.get("title"))}</h2>{_project_blocks(content.get("blocks", []))}{links_html}<nav class="project-adjacent" aria-label="Project navigation">{"".join(adjacent)}</nav></div></div></div></main>{_footer(portfolio)}<script type="module" src="../../assets/js/app.js"></script></body></html>'''


def write_text_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False, newline="\n") as handle:
        handle.write(content + "\n")
        temporary = Path(handle.name)
    os.replace(temporary, path)
